### ISSUE TITLE
Controls section for the README?

### ISSUE THREAD

**Issue by ell1e** [glouw/andvaranaut#10]
*retracted*

**Comment by glouw** [comment]
Oh golly, I haven't touched this project in 3 years. I wrote the graphics engine and got bored with the actual game dev / art work itself. The combat / magic / ranged system you see is no where near done, and I regret trying to implement ranged and magic. A melee hack and slash is the way to go. For what it's worth, with melee weapons, you can draw an attack direction on screen, and the sprites you're hitting will be damaged in that direction.

I should pick up this project again. Maybe make it less violent. Maybe i'll turn it into a farm sim or something :P

**Comment by ell1e** [comment]
Ohh I like combat and scary dungeons though. I just can't figure out what's going on. Is there no damage indicators yet for the enemies? Maybe you could add one, e.g. make them jump up a little vertically when hit (wouldn't need extra animation). Also, I think changing from a gesture system to just click and hit at least for the non-spells would go a long way to increase the responsiveness.

I also wonder if the window could be made resizable? It won't fit my screen:

![windowtoolarge](https://user-images.githubusercontent.com/64124388/128594466-565ec713-7c93-4293-8dac-ad77d7c5252d.png)

**Comment by glouw** [comment]
It really is an old project. It started as an interest in ray casters and once the technical math was out of the way I realized I had no interest in game development. I do not think I will return to this project, sadly.
